name: Verify

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt install -y graphviz
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Verify
        run: mvn -B -U verify
